// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"sort"
)

// DashboardBin represents a single cell on the dashboard
type DashboardBin struct {
	ID       int64
	Name     string
	GridX    int
	GridY    int
	Statuses []string // "critical", "low", "ok", or empty
}

// GetStatusKeys returns the unique, sorted statuses for this bin
func (b DashboardBin) GetStatusKeys() []string {
	unique := make(map[string]bool)
	for _, s := range b.Statuses {
		if s != "" {
			unique[s] = true
		}
	}
	var keys []string
	for k := range unique {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// GetClass returns standard Tailwind utility classes for single-color bins.
func (b DashboardBin) GetClass() string {
	keys := b.GetStatusKeys()

	// Empty Bin
	if len(keys) == 0 {
		return "bg-base-200"
	}

	// Single Status -> Use DaisyUI Utility Classes
	if len(keys) == 1 {
		switch keys[0] {
		case "critical":
			return "bg-error text-error-content"
		case "low":
			return "bg-warning text-warning-content"
		case "ok":
			return "bg-success text-success-content"
		}
	}

	// Multiple Statuses -> Handled by GetStyle()
	return ""
}

// GetStyle returns the gradient string for multi-status bins.
func (b DashboardBin) GetStyle() string {
	keys := b.GetStatusKeys()

	// Single colors are handled by classes, so we return grid position only
	if len(keys) <= 1 {
		return fmt.Sprintf("grid-column: %d; grid-row: %d;", b.GridX+1, b.GridY+1)
	}

	// Map for Gradients (DaisyUI 5 Standard Variables)
	colorMap := map[string]string{
		"critical": "var(--color-error)",
		"low":      "var(--color-warning)",
		"ok":       "var(--color-success)",
	}

	bgStyle := ""

	// Two Colors (Split Diagonal)
	if len(keys) == 2 {
		c1 := colorMap[keys[0]]
		c2 := colorMap[keys[1]]
		bgStyle = fmt.Sprintf("background: linear-gradient(135deg, %s 50%%, %s 50%%);", c1, c2)
	}

	// Three Colors (Pie Chart)
	if len(keys) >= 3 {
		c1 := colorMap[keys[0]]
		c2 := colorMap[keys[1]]
		c3 := colorMap[keys[2]]
		bgStyle = fmt.Sprintf("background: conic-gradient(%s 0deg 120deg, %s 120deg 240deg, %s 240deg 360deg);", c1, c2, c3)
	}

	return fmt.Sprintf("grid-column: %d; grid-row: %d; %s", b.GridX+1, b.GridY+1, bgStyle)
}

func DashboardGrid(bins []DashboardBin) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if len(bins) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"text-center py-12 opacity-50\"><p>No storage grid configured. Go to Hardware to set up your bins.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"card bg-base-100 shadow-xl border border-base-300 overflow-hidden\"><div class=\"card-body p-6\"><h2 class=\"card-title text-2xl mb-6\">Inventory Status</h2><div class=\"overflow-x-auto\"><div class=\"grid gap-1.5 p-1\" style=\"width: fit-content; min-width: 100%;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, bin := range bins {
				var templ_7745c5c3_Var2 = []any{"w-12 h-12 rounded-md border border-base-300/50 flex items-center justify-center text-xs font-bold shadow-sm hover:scale-110 hover:shadow-md hover:z-10 hover:border-base-content/50 transition-all duration-200 cursor-pointer " + bin.GetClass()}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 templ.SafeURL
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(fmt.Sprintf("/parts?bin=%d", bin.ID)))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/dashboard_grid.templ`, Line: 110, Col: 66}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/dashboard_grid.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" style=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(bin.GetStyle())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/dashboard_grid.templ`, Line: 112, Col: 30}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" title=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(bin.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/dashboard_grid.templ`, Line: 113, Col: 24}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"><span class=\"drop-shadow-md filter invert-0 grayscale-0 brightness-100\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(bin.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/dashboard_grid.templ`, Line: 115, Col: 90}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span></a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></div><div class=\"flex gap-4 mt-6 text-xs justify-end opacity-70\"><div class=\"flex items-center gap-2\"><div class=\"w-3 h-3 rounded-full bg-success\"></div>OK</div><div class=\"flex items-center gap-2\"><div class=\"w-3 h-3 rounded-full bg-warning\"></div>Low</div><div class=\"flex items-center gap-2\"><div class=\"w-3 h-3 rounded-full bg-error\"></div>Critical</div><div class=\"flex items-center gap-2\"><div class=\"w-3 h-3 rounded-full bg-base-200 border border-base-300\"></div>Empty</div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
