package qrcode

import (
	"bytes"
	"image/png"
	"testing"
)

func TestPNGRendersScannableQR(t *testing.T) {
	data, err := PNG("wledger:bin:123", 0)
	if err != nil {
		t.Fatalf("PNG failed: %v", err)
	}
	if len(data) == 0 {
		t.Fatal("expected non-empty PNG")
	}
	if _, err := png.Decode(bytes.NewReader(data)); err != nil {
		t.Fatalf("generated bytes are not a valid PNG: %v", err)
	}
}

func TestPNGEmptyContent(t *testing.T) {
	if _, err := PNG("", 0); err == nil {
		t.Fatal("expected error for empty content")
	}
}

func TestPNGUnique(t *testing.T) {
	a, _ := PNG("wledger:bin:1", 0)
	b, _ := PNG("wledger:bin:2", 0)
	if bytes.Equal(a, b) {
		t.Fatal("expected different content to produce different QR codes")
	}
}
