// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bins.sql

package db

import (
	"context"
	"database/sql"
)

const createBin = `-- name: CreateBin :one
INSERT INTO bins (name, controller_id, led_index, width, grid_x, grid_y)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateBinParams struct {
	Name         string        `json:"name"`
	ControllerID sql.NullInt64 `json:"controller_id"`
	LedIndex     sql.NullInt64 `json:"led_index"`
	Width        sql.NullInt64 `json:"width"`
	GridX        sql.NullInt64 `json:"grid_x"`
	GridY        sql.NullInt64 `json:"grid_y"`
}

func (q *Queries) CreateBin(ctx context.Context, arg CreateBinParams) (int64, error) {
	row := q.queryRow(ctx, q.createBinStmt, createBin,
		arg.Name,
		arg.ControllerID,
		arg.LedIndex,
		arg.Width,
		arg.GridX,
		arg.GridY,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBinByLed = `-- name: DeleteBinByLed :exec
DELETE FROM bins 
WHERE controller_id = ? AND led_index = ?
`

type DeleteBinByLedParams struct {
	ControllerID sql.NullInt64 `json:"controller_id"`
	LedIndex     sql.NullInt64 `json:"led_index"`
}

func (q *Queries) DeleteBinByLed(ctx context.Context, arg DeleteBinByLedParams) error {
	_, err := q.exec(ctx, q.deleteBinByLedStmt, deleteBinByLed, arg.ControllerID, arg.LedIndex)
	return err
}

const deleteBinsByController = `-- name: DeleteBinsByController :exec
DELETE FROM bins WHERE controller_id = ?
`

func (q *Queries) DeleteBinsByController(ctx context.Context, controllerID sql.NullInt64) error {
	_, err := q.exec(ctx, q.deleteBinsByControllerStmt, deleteBinsByController, controllerID)
	return err
}

const getBin = `-- name: GetBin :one
SELECT id, name, controller_id, led_index, width, grid_x, grid_y FROM bins WHERE id = ?
`

func (q *Queries) GetBin(ctx context.Context, id int64) (Bin, error) {
	row := q.queryRow(ctx, q.getBinStmt, getBin, id)
	var i Bin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ControllerID,
		&i.LedIndex,
		&i.Width,
		&i.GridX,
		&i.GridY,
	)
	return i, err
}

const getBinsByController = `-- name: GetBinsByController :many
SELECT id, name, controller_id, led_index, width, grid_x, grid_y FROM bins 
WHERE controller_id = ? 
ORDER BY led_index ASC
`

func (q *Queries) GetBinsByController(ctx context.Context, controllerID sql.NullInt64) ([]Bin, error) {
	rows, err := q.query(ctx, q.getBinsByControllerStmt, getBinsByController, controllerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bin
	for rows.Next() {
		var i Bin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ControllerID,
			&i.LedIndex,
			&i.Width,
			&i.GridX,
			&i.GridY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBin = `-- name: UpsertBin :exec
INSERT INTO bins (name, controller_id, led_index, width)
VALUES (?, ?, ?, ?)
ON CONFLICT(controller_id, led_index) DO UPDATE SET
    name = excluded.name,
    width = excluded.width
`

type UpsertBinParams struct {
	Name         string        `json:"name"`
	ControllerID sql.NullInt64 `json:"controller_id"`
	LedIndex     sql.NullInt64 `json:"led_index"`
	Width        sql.NullInt64 `json:"width"`
}

func (q *Queries) UpsertBin(ctx context.Context, arg UpsertBinParams) error {
	_, err := q.exec(ctx, q.upsertBinStmt, upsertBin,
		arg.Name,
		arg.ControllerID,
		arg.LedIndex,
		arg.Width,
	)
	return err
}
