// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bins.sql

package db

import (
	"context"
	"database/sql"
)

const createBin = `-- name: CreateBin :one
INSERT INTO bins (name, controller_id, led_index, width, grid_x, grid_y)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateBinParams struct {
	Name         string        `json:"name"`
	ControllerID sql.NullInt64 `json:"controller_id"`
	LedIndex     sql.NullInt64 `json:"led_index"`
	Width        sql.NullInt64 `json:"width"`
	GridX        sql.NullInt64 `json:"grid_x"`
	GridY        sql.NullInt64 `json:"grid_y"`
}

func (q *Queries) CreateBin(ctx context.Context, arg CreateBinParams) (int64, error) {
	row := q.queryRow(ctx, q.createBinStmt, createBin,
		arg.Name,
		arg.ControllerID,
		arg.LedIndex,
		arg.Width,
		arg.GridX,
		arg.GridY,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBinsByController = `-- name: DeleteBinsByController :exec
DELETE FROM bins WHERE controller_id = ?
`

func (q *Queries) DeleteBinsByController(ctx context.Context, controllerID sql.NullInt64) error {
	_, err := q.exec(ctx, q.deleteBinsByControllerStmt, deleteBinsByController, controllerID)
	return err
}

const getBinsByController = `-- name: GetBinsByController :many
SELECT id, name, controller_id, led_index, width, grid_x, grid_y FROM bins WHERE controller_id = ?
`

func (q *Queries) GetBinsByController(ctx context.Context, controllerID sql.NullInt64) ([]Bin, error) {
	rows, err := q.query(ctx, q.getBinsByControllerStmt, getBinsByController, controllerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bin
	for rows.Next() {
		var i Bin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ControllerID,
			&i.LedIndex,
			&i.Width,
			&i.GridX,
			&i.GridY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
