// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: containers.sql

package db

import (
	"context"
	"database/sql"
)

const createContainer = `-- name: CreateContainer :one
INSERT INTO containers (name, controller_id, segment_id, config_json)
VALUES (?, ?, ?, ?)
RETURNING id
`

type CreateContainerParams struct {
	Name         string         `json:"name"`
	ControllerID int64          `json:"controller_id"`
	SegmentID    int64          `json:"segment_id"`
	ConfigJson   sql.NullString `json:"config_json"`
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) (int64, error) {
	row := q.queryRow(ctx, q.createContainerStmt, createContainer,
		arg.Name,
		arg.ControllerID,
		arg.SegmentID,
		arg.ConfigJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteContainer = `-- name: DeleteContainer :exec
DELETE FROM containers WHERE id = ?
`

func (q *Queries) DeleteContainer(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteContainerStmt, deleteContainer, id)
	return err
}

const getAllContainers = `-- name: GetAllContainers :many
SELECT id, name, controller_id, segment_id, config_json, created_at, updated_at FROM containers ORDER BY name
`

func (q *Queries) GetAllContainers(ctx context.Context) ([]Container, error) {
	rows, err := q.query(ctx, q.getAllContainersStmt, getAllContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ControllerID,
			&i.SegmentID,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContainer = `-- name: GetContainer :one
SELECT id, name, controller_id, segment_id, config_json, created_at, updated_at FROM containers WHERE id = ?
`

func (q *Queries) GetContainer(ctx context.Context, id int64) (Container, error) {
	row := q.queryRow(ctx, q.getContainerStmt, getContainer, id)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ControllerID,
		&i.SegmentID,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContainersByController = `-- name: GetContainersByController :many
SELECT id, name, controller_id, segment_id, config_json, created_at, updated_at FROM containers WHERE controller_id = ? ORDER BY id
`

func (q *Queries) GetContainersByController(ctx context.Context, controllerID int64) ([]Container, error) {
	rows, err := q.query(ctx, q.getContainersByControllerStmt, getContainersByController, controllerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ControllerID,
			&i.SegmentID,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreContainer = `-- name: RestoreContainer :exec
INSERT INTO containers (id, name, controller_id, segment_id, config_json, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type RestoreContainerParams struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	ControllerID int64          `json:"controller_id"`
	SegmentID    int64          `json:"segment_id"`
	ConfigJson   sql.NullString `json:"config_json"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) RestoreContainer(ctx context.Context, arg RestoreContainerParams) error {
	_, err := q.exec(ctx, q.restoreContainerStmt, restoreContainer,
		arg.ID,
		arg.Name,
		arg.ControllerID,
		arg.SegmentID,
		arg.ConfigJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateContainerConfig = `-- name: UpdateContainerConfig :exec
UPDATE containers
SET name = ?, config_json = ?, segment_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateContainerConfigParams struct {
	Name       string         `json:"name"`
	ConfigJson sql.NullString `json:"config_json"`
	SegmentID  int64          `json:"segment_id"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateContainerConfig(ctx context.Context, arg UpdateContainerConfigParams) error {
	_, err := q.exec(ctx, q.updateContainerConfigStmt, updateContainerConfig,
		arg.Name,
		arg.ConfigJson,
		arg.SegmentID,
		arg.ID,
	)
	return err
}
