// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT 
    (SELECT COUNT(*) FROM parts) as total_parts,
    (SELECT COUNT(*) FROM controllers) as total_controllers,
    (SELECT COUNT(*) FROM controllers WHERE is_online = 1) as online_controllers,
    -- CAST to INTEGER so sqlc generates 'int64' instead of 'interface{}'
    (SELECT CAST(COALESCE(SUM(quantity), 0) AS INTEGER) FROM part_assignments) as total_items_in_stock,
    (SELECT COUNT(*) FROM parts WHERE is_favorite = 1) as favorite_parts
`

type GetDashboardStatsRow struct {
	TotalParts        int64 `json:"total_parts"`
	TotalControllers  int64 `json:"total_controllers"`
	OnlineControllers int64 `json:"online_controllers"`
	TotalItemsInStock int64 `json:"total_items_in_stock"`
	FavoriteParts     int64 `json:"favorite_parts"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.queryRow(ctx, q.getDashboardStatsStmt, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalParts,
		&i.TotalControllers,
		&i.OnlineControllers,
		&i.TotalItemsInStock,
		&i.FavoriteParts,
	)
	return i, err
}
