// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parts.sql

package db

import (
	"context"
	"database/sql"
)

const createPart = `-- name: CreatePart :one
INSERT INTO parts (
    name, description, part_number, manufacturer, supplier, 
    unit_cost, reorder_level, min_stock_threshold, 
    image_path, barcode_data
) VALUES (
    ?, ?, ?, ?, ?, 
    ?, ?, ?, 
    ?, ?
) RETURNING id
`

type CreatePartParams struct {
	Name              string          `json:"name"`
	Description       sql.NullString  `json:"description"`
	PartNumber        sql.NullString  `json:"part_number"`
	Manufacturer      sql.NullString  `json:"manufacturer"`
	Supplier          sql.NullString  `json:"supplier"`
	UnitCost          sql.NullFloat64 `json:"unit_cost"`
	ReorderLevel      sql.NullInt64   `json:"reorder_level"`
	MinStockThreshold sql.NullInt64   `json:"min_stock_threshold"`
	ImagePath         sql.NullString  `json:"image_path"`
	BarcodeData       sql.NullString  `json:"barcode_data"`
}

func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) (int64, error) {
	row := q.queryRow(ctx, q.createPartStmt, createPart,
		arg.Name,
		arg.Description,
		arg.PartNumber,
		arg.Manufacturer,
		arg.Supplier,
		arg.UnitCost,
		arg.ReorderLevel,
		arg.MinStockThreshold,
		arg.ImagePath,
		arg.BarcodeData,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPartAssignment = `-- name: CreatePartAssignment :exec
INSERT INTO part_assignments (part_id, bin_id, quantity) VALUES (?, ?, ?)
`

type CreatePartAssignmentParams struct {
	PartID   int64         `json:"part_id"`
	BinID    sql.NullInt64 `json:"bin_id"`
	Quantity int64         `json:"quantity"`
}

func (q *Queries) CreatePartAssignment(ctx context.Context, arg CreatePartAssignmentParams) error {
	_, err := q.exec(ctx, q.createPartAssignmentStmt, createPartAssignment, arg.PartID, arg.BinID, arg.Quantity)
	return err
}

const createPartDoc = `-- name: CreatePartDoc :exec
INSERT INTO part_docs (part_id, file_path, file_name) VALUES (?, ?, ?)
`

type CreatePartDocParams struct {
	PartID   int64  `json:"part_id"`
	FilePath string `json:"file_path"`
	FileName string `json:"file_name"`
}

// DOCUMENTS
func (q *Queries) CreatePartDoc(ctx context.Context, arg CreatePartDocParams) error {
	_, err := q.exec(ctx, q.createPartDocStmt, createPartDoc, arg.PartID, arg.FilePath, arg.FileName)
	return err
}

const createPartLink = `-- name: CreatePartLink :exec
INSERT INTO part_links (part_id, url, label) VALUES (?, ?, ?)
`

type CreatePartLinkParams struct {
	PartID int64          `json:"part_id"`
	Url    string         `json:"url"`
	Label  sql.NullString `json:"label"`
}

// LINKS
func (q *Queries) CreatePartLink(ctx context.Context, arg CreatePartLinkParams) error {
	_, err := q.exec(ctx, q.createPartLinkStmt, createPartLink, arg.PartID, arg.Url, arg.Label)
	return err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM part_assignments WHERE id = ?
`

func (q *Queries) DeleteAssignment(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteAssignmentStmt, deleteAssignment, id)
	return err
}

const deletePart = `-- name: DeletePart :exec
DELETE FROM parts WHERE id = ?
`

func (q *Queries) DeletePart(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deletePartStmt, deletePart, id)
	return err
}

const deletePartAssignment = `-- name: DeletePartAssignment :exec
DELETE FROM part_assignments WHERE part_id = ? AND bin_id = ?
`

type DeletePartAssignmentParams struct {
	PartID int64         `json:"part_id"`
	BinID  sql.NullInt64 `json:"bin_id"`
}

func (q *Queries) DeletePartAssignment(ctx context.Context, arg DeletePartAssignmentParams) error {
	_, err := q.exec(ctx, q.deletePartAssignmentStmt, deletePartAssignment, arg.PartID, arg.BinID)
	return err
}

const deletePartDoc = `-- name: DeletePartDoc :exec
DELETE FROM part_docs WHERE id = ?
`

func (q *Queries) DeletePartDoc(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deletePartDocStmt, deletePartDoc, id)
	return err
}

const deletePartLink = `-- name: DeletePartLink :exec
DELETE FROM part_links WHERE id = ?
`

func (q *Queries) DeletePartLink(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deletePartLinkStmt, deletePartLink, id)
	return err
}

const getAllPartAiPrompts = `-- name: GetAllPartAiPrompts :many
SELECT id, part_id, prompt_text, ai_response, model_used, created_at FROM part_ai_prompts ORDER BY id
`

func (q *Queries) GetAllPartAiPrompts(ctx context.Context) ([]PartAiPrompt, error) {
	rows, err := q.query(ctx, q.getAllPartAiPromptsStmt, getAllPartAiPrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartAiPrompt
	for rows.Next() {
		var i PartAiPrompt
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.PromptText,
			&i.AiResponse,
			&i.ModelUsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPartAssignments = `-- name: GetAllPartAssignments :many
SELECT id, part_id, bin_id, quantity FROM part_assignments ORDER BY id
`

// STOCK ASSIGNMENTS
func (q *Queries) GetAllPartAssignments(ctx context.Context) ([]PartAssignment, error) {
	rows, err := q.query(ctx, q.getAllPartAssignmentsStmt, getAllPartAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartAssignment
	for rows.Next() {
		var i PartAssignment
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.BinID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPartDocs = `-- name: GetAllPartDocs :many
SELECT id, part_id, file_path, file_name FROM part_docs ORDER BY id
`

func (q *Queries) GetAllPartDocs(ctx context.Context) ([]PartDoc, error) {
	rows, err := q.query(ctx, q.getAllPartDocsStmt, getAllPartDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartDoc
	for rows.Next() {
		var i PartDoc
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.FilePath,
			&i.FileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPartLinks = `-- name: GetAllPartLinks :many
SELECT id, part_id, url, label FROM part_links ORDER BY id
`

func (q *Queries) GetAllPartLinks(ctx context.Context) ([]PartLink, error) {
	rows, err := q.query(ctx, q.getAllPartLinksStmt, getAllPartLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartLink
	for rows.Next() {
		var i PartLink
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.Url,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllParts = `-- name: GetAllParts :many
SELECT id, name, description, part_number, manufacturer, supplier, unit_cost, reorder_level, min_stock_threshold, barcode_data, image_path, is_favorite, created_at, updated_at FROM parts ORDER BY id
`

func (q *Queries) GetAllParts(ctx context.Context) ([]Part, error) {
	rows, err := q.query(ctx, q.getAllPartsStmt, getAllParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Part
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PartNumber,
			&i.Manufacturer,
			&i.Supplier,
			&i.UnitCost,
			&i.ReorderLevel,
			&i.MinStockThreshold,
			&i.BarcodeData,
			&i.ImagePath,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, part_id, bin_id, quantity FROM part_assignments WHERE id = ?
`

func (q *Queries) GetAssignment(ctx context.Context, id int64) (PartAssignment, error) {
	row := q.queryRow(ctx, q.getAssignmentStmt, getAssignment, id)
	var i PartAssignment
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.BinID,
		&i.Quantity,
	)
	return i, err
}

const getAssignmentID = `-- name: GetAssignmentID :one
SELECT id FROM part_assignments WHERE part_id = ? AND bin_id = ?
`

type GetAssignmentIDParams struct {
	PartID int64         `json:"part_id"`
	BinID  sql.NullInt64 `json:"bin_id"`
}

func (q *Queries) GetAssignmentID(ctx context.Context, arg GetAssignmentIDParams) (int64, error) {
	row := q.queryRow(ctx, q.getAssignmentIDStmt, getAssignmentID, arg.PartID, arg.BinID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPart = `-- name: GetPart :one
SELECT id, name, description, part_number, manufacturer, supplier, unit_cost, reorder_level, min_stock_threshold, barcode_data, image_path, is_favorite, created_at, updated_at FROM parts WHERE id = ?
`

func (q *Queries) GetPart(ctx context.Context, id int64) (Part, error) {
	row := q.queryRow(ctx, q.getPartStmt, getPart, id)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PartNumber,
		&i.Manufacturer,
		&i.Supplier,
		&i.UnitCost,
		&i.ReorderLevel,
		&i.MinStockThreshold,
		&i.BarcodeData,
		&i.ImagePath,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartAssignments = `-- name: GetPartAssignments :many
SELECT 
    pa.id, 
    pa.quantity, 
    b.id as bin_id, 
    b.name as bin_name,
    c.name as controller_name,
    c.id as controller_id,
    c.ip_address as controller_ip
FROM part_assignments pa
LEFT JOIN bins b ON pa.bin_id = b.id
LEFT JOIN controllers c ON b.controller_id = c.id
WHERE pa.part_id = ?
`

type GetPartAssignmentsRow struct {
	ID             int64          `json:"id"`
	Quantity       int64          `json:"quantity"`
	BinID          sql.NullInt64  `json:"bin_id"`
	BinName        sql.NullString `json:"bin_name"`
	ControllerName sql.NullString `json:"controller_name"`
	ControllerID   sql.NullInt64  `json:"controller_id"`
	ControllerIp   sql.NullString `json:"controller_ip"`
}

func (q *Queries) GetPartAssignments(ctx context.Context, partID int64) ([]GetPartAssignmentsRow, error) {
	rows, err := q.query(ctx, q.getPartAssignmentsStmt, getPartAssignments, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartAssignmentsRow
	for rows.Next() {
		var i GetPartAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.BinID,
			&i.BinName,
			&i.ControllerName,
			&i.ControllerID,
			&i.ControllerIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartDoc = `-- name: GetPartDoc :one
SELECT id, part_id, file_path, file_name FROM part_docs WHERE id = ?
`

func (q *Queries) GetPartDoc(ctx context.Context, id int64) (PartDoc, error) {
	row := q.queryRow(ctx, q.getPartDocStmt, getPartDoc, id)
	var i PartDoc
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.FilePath,
		&i.FileName,
	)
	return i, err
}

const getPartDocs = `-- name: GetPartDocs :many
SELECT id, part_id, file_path, file_name FROM part_docs WHERE part_id = ?
`

func (q *Queries) GetPartDocs(ctx context.Context, partID int64) ([]PartDoc, error) {
	rows, err := q.query(ctx, q.getPartDocsStmt, getPartDocs, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartDoc
	for rows.Next() {
		var i PartDoc
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.FilePath,
			&i.FileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartLinks = `-- name: GetPartLinks :many
SELECT id, part_id, url, label FROM part_links WHERE part_id = ?
`

func (q *Queries) GetPartLinks(ctx context.Context, partID int64) ([]PartLink, error) {
	rows, err := q.query(ctx, q.getPartLinksStmt, getPartLinks, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartLink
	for rows.Next() {
		var i PartLink
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.Url,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParts = `-- name: ListParts :many
SELECT id, name, description, part_number, manufacturer, supplier, unit_cost, reorder_level, min_stock_threshold, barcode_data, image_path, is_favorite, created_at, updated_at, 
    (SELECT COALESCE(SUM(quantity), 0) FROM part_assignments WHERE part_id = parts.id) as total_stock 
FROM parts 
ORDER BY name 
LIMIT ? OFFSET ?
`

type ListPartsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListPartsRow struct {
	ID                int64           `json:"id"`
	Name              string          `json:"name"`
	Description       sql.NullString  `json:"description"`
	PartNumber        sql.NullString  `json:"part_number"`
	Manufacturer      sql.NullString  `json:"manufacturer"`
	Supplier          sql.NullString  `json:"supplier"`
	UnitCost          sql.NullFloat64 `json:"unit_cost"`
	ReorderLevel      sql.NullInt64   `json:"reorder_level"`
	MinStockThreshold sql.NullInt64   `json:"min_stock_threshold"`
	BarcodeData       sql.NullString  `json:"barcode_data"`
	ImagePath         sql.NullString  `json:"image_path"`
	IsFavorite        sql.NullBool    `json:"is_favorite"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
	TotalStock        interface{}     `json:"total_stock"`
}

func (q *Queries) ListParts(ctx context.Context, arg ListPartsParams) ([]ListPartsRow, error) {
	rows, err := q.query(ctx, q.listPartsStmt, listParts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartsRow
	for rows.Next() {
		var i ListPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PartNumber,
			&i.Manufacturer,
			&i.Supplier,
			&i.UnitCost,
			&i.ReorderLevel,
			&i.MinStockThreshold,
			&i.BarcodeData,
			&i.ImagePath,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignPartAssignment = `-- name: ReassignPartAssignment :exec
UPDATE part_assignments 
SET bin_id = ? 
WHERE id = ?
`

type ReassignPartAssignmentParams struct {
	BinID sql.NullInt64 `json:"bin_id"`
	ID    int64         `json:"id"`
}

func (q *Queries) ReassignPartAssignment(ctx context.Context, arg ReassignPartAssignmentParams) error {
	_, err := q.exec(ctx, q.reassignPartAssignmentStmt, reassignPartAssignment, arg.BinID, arg.ID)
	return err
}

const restorePart = `-- name: RestorePart :exec
INSERT INTO parts (
    id, name, description, part_number, manufacturer, supplier, 
    unit_cost, reorder_level, min_stock_threshold, 
    image_path, barcode_data, is_favorite, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, 
    ?, ?, ?, 
    ?, ?, ?, ?, ?
)
`

type RestorePartParams struct {
	ID                int64           `json:"id"`
	Name              string          `json:"name"`
	Description       sql.NullString  `json:"description"`
	PartNumber        sql.NullString  `json:"part_number"`
	Manufacturer      sql.NullString  `json:"manufacturer"`
	Supplier          sql.NullString  `json:"supplier"`
	UnitCost          sql.NullFloat64 `json:"unit_cost"`
	ReorderLevel      sql.NullInt64   `json:"reorder_level"`
	MinStockThreshold sql.NullInt64   `json:"min_stock_threshold"`
	ImagePath         sql.NullString  `json:"image_path"`
	BarcodeData       sql.NullString  `json:"barcode_data"`
	IsFavorite        sql.NullBool    `json:"is_favorite"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
}

func (q *Queries) RestorePart(ctx context.Context, arg RestorePartParams) error {
	_, err := q.exec(ctx, q.restorePartStmt, restorePart,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PartNumber,
		arg.Manufacturer,
		arg.Supplier,
		arg.UnitCost,
		arg.ReorderLevel,
		arg.MinStockThreshold,
		arg.ImagePath,
		arg.BarcodeData,
		arg.IsFavorite,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const restorePartAiPrompt = `-- name: RestorePartAiPrompt :exec
INSERT INTO part_ai_prompts (id, part_id, prompt_text, ai_response, model_used, created_at) VALUES (?, ?, ?, ?, ?, ?)
`

type RestorePartAiPromptParams struct {
	ID         int64          `json:"id"`
	PartID     int64          `json:"part_id"`
	PromptText string         `json:"prompt_text"`
	AiResponse sql.NullString `json:"ai_response"`
	ModelUsed  sql.NullString `json:"model_used"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

func (q *Queries) RestorePartAiPrompt(ctx context.Context, arg RestorePartAiPromptParams) error {
	_, err := q.exec(ctx, q.restorePartAiPromptStmt, restorePartAiPrompt,
		arg.ID,
		arg.PartID,
		arg.PromptText,
		arg.AiResponse,
		arg.ModelUsed,
		arg.CreatedAt,
	)
	return err
}

const restorePartAssignment = `-- name: RestorePartAssignment :exec
INSERT INTO part_assignments (id, part_id, bin_id, quantity) VALUES (?, ?, ?, ?)
`

type RestorePartAssignmentParams struct {
	ID       int64         `json:"id"`
	PartID   int64         `json:"part_id"`
	BinID    sql.NullInt64 `json:"bin_id"`
	Quantity int64         `json:"quantity"`
}

func (q *Queries) RestorePartAssignment(ctx context.Context, arg RestorePartAssignmentParams) error {
	_, err := q.exec(ctx, q.restorePartAssignmentStmt, restorePartAssignment,
		arg.ID,
		arg.PartID,
		arg.BinID,
		arg.Quantity,
	)
	return err
}

const restorePartDoc = `-- name: RestorePartDoc :exec
INSERT INTO part_docs (id, part_id, file_path, file_name) VALUES (?, ?, ?, ?)
`

type RestorePartDocParams struct {
	ID       int64  `json:"id"`
	PartID   int64  `json:"part_id"`
	FilePath string `json:"file_path"`
	FileName string `json:"file_name"`
}

func (q *Queries) RestorePartDoc(ctx context.Context, arg RestorePartDocParams) error {
	_, err := q.exec(ctx, q.restorePartDocStmt, restorePartDoc,
		arg.ID,
		arg.PartID,
		arg.FilePath,
		arg.FileName,
	)
	return err
}

const restorePartLink = `-- name: RestorePartLink :exec
INSERT INTO part_links (id, part_id, url, label) VALUES (?, ?, ?, ?)
`

type RestorePartLinkParams struct {
	ID     int64          `json:"id"`
	PartID int64          `json:"part_id"`
	Url    string         `json:"url"`
	Label  sql.NullString `json:"label"`
}

func (q *Queries) RestorePartLink(ctx context.Context, arg RestorePartLinkParams) error {
	_, err := q.exec(ctx, q.restorePartLinkStmt, restorePartLink,
		arg.ID,
		arg.PartID,
		arg.Url,
		arg.Label,
	)
	return err
}

const searchParts = `-- name: SearchParts :many
SELECT p.id, p.name, p.description, p.part_number, p.manufacturer, p.supplier, p.unit_cost, p.reorder_level, p.min_stock_threshold, p.barcode_data, p.image_path, p.is_favorite, p.created_at, p.updated_at, 
    (SELECT COALESCE(SUM(quantity), 0) FROM part_assignments WHERE part_id = p.id) as total_stock 
FROM parts_fts 
JOIN parts p ON parts_fts.rowid = p.id 
WHERE parts_fts MATCH ? 
ORDER BY parts_fts.rank
LIMIT ? OFFSET ?
`

type SearchPartsParams struct {
	PartsFts sql.NullString `json:"parts_fts"`
	Limit    int64          `json:"limit"`
	Offset   int64          `json:"offset"`
}

type SearchPartsRow struct {
	ID                int64           `json:"id"`
	Name              string          `json:"name"`
	Description       sql.NullString  `json:"description"`
	PartNumber        sql.NullString  `json:"part_number"`
	Manufacturer      sql.NullString  `json:"manufacturer"`
	Supplier          sql.NullString  `json:"supplier"`
	UnitCost          sql.NullFloat64 `json:"unit_cost"`
	ReorderLevel      sql.NullInt64   `json:"reorder_level"`
	MinStockThreshold sql.NullInt64   `json:"min_stock_threshold"`
	BarcodeData       sql.NullString  `json:"barcode_data"`
	ImagePath         sql.NullString  `json:"image_path"`
	IsFavorite        sql.NullBool    `json:"is_favorite"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
	TotalStock        interface{}     `json:"total_stock"`
}

func (q *Queries) SearchParts(ctx context.Context, arg SearchPartsParams) ([]SearchPartsRow, error) {
	rows, err := q.query(ctx, q.searchPartsStmt, searchParts, arg.PartsFts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPartsRow
	for rows.Next() {
		var i SearchPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PartNumber,
			&i.Manufacturer,
			&i.Supplier,
			&i.UnitCost,
			&i.ReorderLevel,
			&i.MinStockThreshold,
			&i.BarcodeData,
			&i.ImagePath,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePart = `-- name: UpdatePart :exec
UPDATE parts SET 
    name = ?, 
    description = ?, 
    part_number = ?, 
    manufacturer = ?, 
    supplier = ?, 
    unit_cost = ?, 
    reorder_level = ?, 
    min_stock_threshold = ?, 
    barcode_data = ?,
    image_path = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePartParams struct {
	Name              string          `json:"name"`
	Description       sql.NullString  `json:"description"`
	PartNumber        sql.NullString  `json:"part_number"`
	Manufacturer      sql.NullString  `json:"manufacturer"`
	Supplier          sql.NullString  `json:"supplier"`
	UnitCost          sql.NullFloat64 `json:"unit_cost"`
	ReorderLevel      sql.NullInt64   `json:"reorder_level"`
	MinStockThreshold sql.NullInt64   `json:"min_stock_threshold"`
	BarcodeData       sql.NullString  `json:"barcode_data"`
	ImagePath         sql.NullString  `json:"image_path"`
	ID                int64           `json:"id"`
}

func (q *Queries) UpdatePart(ctx context.Context, arg UpdatePartParams) error {
	_, err := q.exec(ctx, q.updatePartStmt, updatePart,
		arg.Name,
		arg.Description,
		arg.PartNumber,
		arg.Manufacturer,
		arg.Supplier,
		arg.UnitCost,
		arg.ReorderLevel,
		arg.MinStockThreshold,
		arg.BarcodeData,
		arg.ImagePath,
		arg.ID,
	)
	return err
}

const updatePartAssignmentQuantity = `-- name: UpdatePartAssignmentQuantity :exec
UPDATE part_assignments SET quantity = ? WHERE part_id = ? AND bin_id = ?
`

type UpdatePartAssignmentQuantityParams struct {
	Quantity int64         `json:"quantity"`
	PartID   int64         `json:"part_id"`
	BinID    sql.NullInt64 `json:"bin_id"`
}

func (q *Queries) UpdatePartAssignmentQuantity(ctx context.Context, arg UpdatePartAssignmentQuantityParams) error {
	_, err := q.exec(ctx, q.updatePartAssignmentQuantityStmt, updatePartAssignmentQuantity, arg.Quantity, arg.PartID, arg.BinID)
	return err
}
