// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CleanupSessions(ctx context.Context, expiry float64) error
	CountUsers(ctx context.Context) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteSession(ctx context.Context, token string) error
	GetSession(ctx context.Context, token string) (Session, error)
	GetSettings(ctx context.Context) (Setting, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InitSettings(ctx context.Context) error
	UpdateColors(ctx context.Context, arg UpdateColorsParams) error
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error
}

var _ Querier = (*Queries)(nil)
