// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
	"database/sql"
)

const getSettings = `-- name: GetSettings :one
SELECT id, require_auth_for_read, locate_timeout_seconds, enable_locate_timeout, enable_debug_logs, color_locate, color_stock_ok, color_stock_low, color_stock_critical, created_at, updated_at, inspiration_seeds_applied FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.queryRow(ctx, q.getSettingsStmt, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.RequireAuthForRead,
		&i.LocateTimeoutSeconds,
		&i.EnableLocateTimeout,
		&i.EnableDebugLogs,
		&i.ColorLocate,
		&i.ColorStockOk,
		&i.ColorStockLow,
		&i.ColorStockCritical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InspirationSeedsApplied,
	)
	return i, err
}

const initSettings = `-- name: InitSettings :exec
INSERT OR IGNORE INTO settings (id, require_auth_for_read, color_locate, color_stock_ok, color_stock_low, color_stock_critical, locate_timeout_seconds, enable_locate_timeout, enable_debug_logs)
VALUES (1, 1, '#0000FF', '#00FF00', '#FFFF00', '#FF0000', 10, 1, 0)
`

func (q *Queries) InitSettings(ctx context.Context) error {
	_, err := q.exec(ctx, q.initSettingsStmt, initSettings)
	return err
}

const markInspirationSeedsApplied = `-- name: MarkInspirationSeedsApplied :exec

UPDATE settings

SET inspiration_seeds_applied = 1, updated_at = CURRENT_TIMESTAMP

WHERE id = 1
`

func (q *Queries) MarkInspirationSeedsApplied(ctx context.Context) error {
	_, err := q.exec(ctx, q.markInspirationSeedsAppliedStmt, markInspirationSeedsApplied)
	return err
}

const restoreSettings = `-- name: RestoreSettings :exec
INSERT INTO settings (
    id, require_auth_for_read, locate_timeout_seconds, enable_locate_timeout, 
    color_locate, color_stock_ok, color_stock_low, color_stock_critical, 
    created_at, updated_at, enable_debug_logs
) VALUES (
    1, ?, ?, ?, 
    ?, ?, ?, ?, 
    ?, ?, ?
)
`

type RestoreSettingsParams struct {
	RequireAuthForRead   sql.NullBool   `json:"require_auth_for_read"`
	LocateTimeoutSeconds sql.NullInt64  `json:"locate_timeout_seconds"`
	EnableLocateTimeout  sql.NullBool   `json:"enable_locate_timeout"`
	ColorLocate          sql.NullString `json:"color_locate"`
	ColorStockOk         sql.NullString `json:"color_stock_ok"`
	ColorStockLow        sql.NullString `json:"color_stock_low"`
	ColorStockCritical   sql.NullString `json:"color_stock_critical"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	EnableDebugLogs      sql.NullBool   `json:"enable_debug_logs"`
}

func (q *Queries) RestoreSettings(ctx context.Context, arg RestoreSettingsParams) error {
	_, err := q.exec(ctx, q.restoreSettingsStmt, restoreSettings,
		arg.RequireAuthForRead,
		arg.LocateTimeoutSeconds,
		arg.EnableLocateTimeout,
		arg.ColorLocate,
		arg.ColorStockOk,
		arg.ColorStockLow,
		arg.ColorStockCritical,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EnableDebugLogs,
	)
	return err
}

const updateColors = `-- name: UpdateColors :exec

UPDATE settings

SET color_locate = ?, color_stock_ok = ?, color_stock_low = ?, color_stock_critical = ?, updated_at = CURRENT_TIMESTAMP

WHERE id = 1
`

type UpdateColorsParams struct {
	ColorLocate        sql.NullString `json:"color_locate"`
	ColorStockOk       sql.NullString `json:"color_stock_ok"`
	ColorStockLow      sql.NullString `json:"color_stock_low"`
	ColorStockCritical sql.NullString `json:"color_stock_critical"`
}

func (q *Queries) UpdateColors(ctx context.Context, arg UpdateColorsParams) error {
	_, err := q.exec(ctx, q.updateColorsStmt, updateColors,
		arg.ColorLocate,
		arg.ColorStockOk,
		arg.ColorStockLow,
		arg.ColorStockCritical,
	)
	return err
}

const updateGeneralSettings = `-- name: UpdateGeneralSettings :exec
UPDATE settings 
SET require_auth_for_read = ?, locate_timeout_seconds = ?, enable_locate_timeout = ?, enable_debug_logs = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

type UpdateGeneralSettingsParams struct {
	RequireAuthForRead   sql.NullBool  `json:"require_auth_for_read"`
	LocateTimeoutSeconds sql.NullInt64 `json:"locate_timeout_seconds"`
	EnableLocateTimeout  sql.NullBool  `json:"enable_locate_timeout"`
	EnableDebugLogs      sql.NullBool  `json:"enable_debug_logs"`
}

func (q *Queries) UpdateGeneralSettings(ctx context.Context, arg UpdateGeneralSettingsParams) error {
	_, err := q.exec(ctx, q.updateGeneralSettingsStmt, updateGeneralSettings,
		arg.RequireAuthForRead,
		arg.LocateTimeoutSeconds,
		arg.EnableLocateTimeout,
		arg.EnableDebugLogs,
	)
	return err
}
