// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
	"database/sql"
)

const getSettings = `-- name: GetSettings :one
SELECT id, require_auth_for_read, locate_timeout_seconds, enable_locate_timeout, color_locate, color_stock_ok, color_stock_low, color_stock_critical, created_at, updated_at FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.queryRow(ctx, q.getSettingsStmt, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.RequireAuthForRead,
		&i.LocateTimeoutSeconds,
		&i.EnableLocateTimeout,
		&i.ColorLocate,
		&i.ColorStockOk,
		&i.ColorStockLow,
		&i.ColorStockCritical,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const initSettings = `-- name: InitSettings :exec
INSERT OR IGNORE INTO settings (id) VALUES (1)
`

func (q *Queries) InitSettings(ctx context.Context) error {
	_, err := q.exec(ctx, q.initSettingsStmt, initSettings)
	return err
}

const updateColors = `-- name: UpdateColors :exec
UPDATE settings
SET color_locate = ?, color_stock_ok = ?, color_stock_low = ?, color_stock_critical = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

type UpdateColorsParams struct {
	ColorLocate        sql.NullString `json:"color_locate"`
	ColorStockOk       sql.NullString `json:"color_stock_ok"`
	ColorStockLow      sql.NullString `json:"color_stock_low"`
	ColorStockCritical sql.NullString `json:"color_stock_critical"`
}

func (q *Queries) UpdateColors(ctx context.Context, arg UpdateColorsParams) error {
	_, err := q.exec(ctx, q.updateColorsStmt, updateColors,
		arg.ColorLocate,
		arg.ColorStockOk,
		arg.ColorStockLow,
		arg.ColorStockCritical,
	)
	return err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings 
SET locate_timeout_seconds = ?, enable_locate_timeout = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

type UpdateSettingsParams struct {
	LocateTimeoutSeconds sql.NullInt64 `json:"locate_timeout_seconds"`
	EnableLocateTimeout  sql.NullBool  `json:"enable_locate_timeout"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.exec(ctx, q.updateSettingsStmt, updateSettings, arg.LocateTimeoutSeconds, arg.EnableLocateTimeout)
	return err
}
