// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: supplier_references.sql

package db

import (
	"context"
	"database/sql"
)

const clearSupplierReferences = `-- name: ClearSupplierReferences :exec
DELETE FROM supplier_references
`

func (q *Queries) ClearSupplierReferences(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearSupplierReferencesStmt, clearSupplierReferences)
	return err
}

const createSupplierReference = `-- name: CreateSupplierReference :one
INSERT INTO supplier_references (part_id, provider_key, provider_id, provider_url)
VALUES (?, ?, ?, ?)
RETURNING id
`

type CreateSupplierReferenceParams struct {
	PartID      int64          `json:"part_id"`
	ProviderKey string         `json:"provider_key"`
	ProviderID  string         `json:"provider_id"`
	ProviderUrl sql.NullString `json:"provider_url"`
}

func (q *Queries) CreateSupplierReference(ctx context.Context, arg CreateSupplierReferenceParams) (int64, error) {
	row := q.queryRow(ctx, q.createSupplierReferenceStmt, createSupplierReference,
		arg.PartID,
		arg.ProviderKey,
		arg.ProviderID,
		arg.ProviderUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSupplierReference = `-- name: DeleteSupplierReference :exec
DELETE FROM supplier_references WHERE id = ?
`

func (q *Queries) DeleteSupplierReference(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteSupplierReferenceStmt, deleteSupplierReference, id)
	return err
}

const deleteSupplierReferencesByPart = `-- name: DeleteSupplierReferencesByPart :exec
DELETE FROM supplier_references WHERE part_id = ?
`

func (q *Queries) DeleteSupplierReferencesByPart(ctx context.Context, partID int64) error {
	_, err := q.exec(ctx, q.deleteSupplierReferencesByPartStmt, deleteSupplierReferencesByPart, partID)
	return err
}

const findExistingPartByProviderRef = `-- name: FindExistingPartByProviderRef :one
SELECT p.id, p.name, p.description, p.part_number, p.manufacturer, p.supplier, p.unit_cost, p.reorder_level, p.min_stock_threshold, p.barcode_data, p.image_path, p.is_favorite, p.tags, p.created_at, p.updated_at, p.footprint FROM parts p
JOIN supplier_references sr ON p.id = sr.part_id
WHERE sr.provider_key = ? AND sr.provider_id = ?
`

type FindExistingPartByProviderRefParams struct {
	ProviderKey string `json:"provider_key"`
	ProviderID  string `json:"provider_id"`
}

func (q *Queries) FindExistingPartByProviderRef(ctx context.Context, arg FindExistingPartByProviderRefParams) (Part, error) {
	row := q.queryRow(ctx, q.findExistingPartByProviderRefStmt, findExistingPartByProviderRef, arg.ProviderKey, arg.ProviderID)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PartNumber,
		&i.Manufacturer,
		&i.Supplier,
		&i.UnitCost,
		&i.ReorderLevel,
		&i.MinStockThreshold,
		&i.BarcodeData,
		&i.ImagePath,
		&i.IsFavorite,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Footprint,
	)
	return i, err
}

const getAllSupplierReferences = `-- name: GetAllSupplierReferences :many
SELECT id, part_id, provider_key, provider_id, provider_url, created_at FROM supplier_references ORDER BY id
`

func (q *Queries) GetAllSupplierReferences(ctx context.Context) ([]SupplierReference, error) {
	rows, err := q.query(ctx, q.getAllSupplierReferencesStmt, getAllSupplierReferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierReference
	for rows.Next() {
		var i SupplierReference
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.ProviderKey,
			&i.ProviderID,
			&i.ProviderUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceComparisonByPart = `-- name: GetPriceComparisonByPart :many
SELECT sr.provider_key, pp.min_quantity, pp.price, pp.currency, pp.includes_tax
FROM part_pricing pp
JOIN supplier_references sr ON pp.supplier_ref_id = sr.id
WHERE sr.part_id = ?
ORDER BY pp.min_quantity ASC, sr.provider_key
`

type GetPriceComparisonByPartRow struct {
	ProviderKey string       `json:"provider_key"`
	MinQuantity int64        `json:"min_quantity"`
	Price       float64      `json:"price"`
	Currency    string       `json:"currency"`
	IncludesTax sql.NullBool `json:"includes_tax"`
}

func (q *Queries) GetPriceComparisonByPart(ctx context.Context, partID int64) ([]GetPriceComparisonByPartRow, error) {
	rows, err := q.query(ctx, q.getPriceComparisonByPartStmt, getPriceComparisonByPart, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPriceComparisonByPartRow
	for rows.Next() {
		var i GetPriceComparisonByPartRow
		if err := rows.Scan(
			&i.ProviderKey,
			&i.MinQuantity,
			&i.Price,
			&i.Currency,
			&i.IncludesTax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyImportedParts = `-- name: GetRecentlyImportedParts :many
SELECT DISTINCT p.id, p.name, p.description, p.part_number, p.manufacturer, p.supplier, p.unit_cost, p.reorder_level, p.min_stock_threshold, p.barcode_data, p.image_path, p.is_favorite, p.tags, p.created_at, p.updated_at, p.footprint, sr.provider_key, sr.created_at AS imported_at
FROM parts p
JOIN supplier_references sr ON p.id = sr.part_id
ORDER BY sr.created_at DESC
LIMIT ?
`

type GetRecentlyImportedPartsRow struct {
	ID                int64           `json:"id"`
	Name              string          `json:"name"`
	Description       sql.NullString  `json:"description"`
	PartNumber        sql.NullString  `json:"part_number"`
	Manufacturer      sql.NullString  `json:"manufacturer"`
	Supplier          sql.NullString  `json:"supplier"`
	UnitCost          sql.NullFloat64 `json:"unit_cost"`
	ReorderLevel      sql.NullInt64   `json:"reorder_level"`
	MinStockThreshold sql.NullInt64   `json:"min_stock_threshold"`
	BarcodeData       sql.NullString  `json:"barcode_data"`
	ImagePath         sql.NullString  `json:"image_path"`
	IsFavorite        sql.NullBool    `json:"is_favorite"`
	Tags              sql.NullString  `json:"tags"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
	Footprint         sql.NullString  `json:"footprint"`
	ProviderKey       string          `json:"provider_key"`
	ImportedAt        sql.NullTime    `json:"imported_at"`
}

func (q *Queries) GetRecentlyImportedParts(ctx context.Context, limit int64) ([]GetRecentlyImportedPartsRow, error) {
	rows, err := q.query(ctx, q.getRecentlyImportedPartsStmt, getRecentlyImportedParts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyImportedPartsRow
	for rows.Next() {
		var i GetRecentlyImportedPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PartNumber,
			&i.Manufacturer,
			&i.Supplier,
			&i.UnitCost,
			&i.ReorderLevel,
			&i.MinStockThreshold,
			&i.BarcodeData,
			&i.ImagePath,
			&i.IsFavorite,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Footprint,
			&i.ProviderKey,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierReference = `-- name: GetSupplierReference :one
SELECT id, part_id, provider_key, provider_id, provider_url, created_at FROM supplier_references WHERE id = ?
`

func (q *Queries) GetSupplierReference(ctx context.Context, id int64) (SupplierReference, error) {
	row := q.queryRow(ctx, q.getSupplierReferenceStmt, getSupplierReference, id)
	var i SupplierReference
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.ProviderKey,
		&i.ProviderID,
		&i.ProviderUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierReferenceByProvider = `-- name: GetSupplierReferenceByProvider :one
SELECT id, part_id, provider_key, provider_id, provider_url, created_at FROM supplier_references WHERE provider_key = ? AND provider_id = ?
`

type GetSupplierReferenceByProviderParams struct {
	ProviderKey string `json:"provider_key"`
	ProviderID  string `json:"provider_id"`
}

func (q *Queries) GetSupplierReferenceByProvider(ctx context.Context, arg GetSupplierReferenceByProviderParams) (SupplierReference, error) {
	row := q.queryRow(ctx, q.getSupplierReferenceByProviderStmt, getSupplierReferenceByProvider, arg.ProviderKey, arg.ProviderID)
	var i SupplierReference
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.ProviderKey,
		&i.ProviderID,
		&i.ProviderUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierReferencesByPart = `-- name: GetSupplierReferencesByPart :many
SELECT id, part_id, provider_key, provider_id, provider_url, created_at FROM supplier_references WHERE part_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetSupplierReferencesByPart(ctx context.Context, partID int64) ([]SupplierReference, error) {
	rows, err := q.query(ctx, q.getSupplierReferencesByPartStmt, getSupplierReferencesByPart, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierReference
	for rows.Next() {
		var i SupplierReference
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.ProviderKey,
			&i.ProviderID,
			&i.ProviderUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreSupplierReference = `-- name: RestoreSupplierReference :exec
INSERT INTO supplier_references (id, part_id, provider_key, provider_id, provider_url, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type RestoreSupplierReferenceParams struct {
	ID          int64          `json:"id"`
	PartID      int64          `json:"part_id"`
	ProviderKey string         `json:"provider_key"`
	ProviderID  string         `json:"provider_id"`
	ProviderUrl sql.NullString `json:"provider_url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) RestoreSupplierReference(ctx context.Context, arg RestoreSupplierReferenceParams) error {
	_, err := q.exec(ctx, q.restoreSupplierReferenceStmt, restoreSupplierReference,
		arg.ID,
		arg.PartID,
		arg.ProviderKey,
		arg.ProviderID,
		arg.ProviderUrl,
		arg.CreatedAt,
	)
	return err
}
